language: ruby
rvm:
    - 2.1.1
    - 2.0.0-p481
    - 1.9.3-p484
env:
    - PUPPET_VERSION=3.7.1
    - PUPPET_VERSION=3.6.2
    - PUPPET_VERSION=3.5.1
before_install:
    - bundle --version
    - gem --version
script:
    - bundle exec rake lint
    - bundle exec rake spec
notifications:
    email: false
